package sistemasinteligentes.view.graphics;

import javax.swing.JOptionPane;
import sistemasinteligentes.model.Agent;
import sistemasinteligentes.view.IPrintable;
import sistemasinteligentes.view.IRenderizable;


public class GUI extends javax.swing.JFrame {
    private Agent agent;
    private AbstractTextPrinter printer;
    
    public GUI() {
        initComponents();
        printer = new JTextAreaPrinter(terminalBox);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        terminalScroll = new javax.swing.JScrollPane();
        terminalBox = new javax.swing.JTextArea();
        continueButton = new javax.swing.JButton();
        renderPanel = new sistemasinteligentes.view.graphics.RenderPanel();
        resetarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        terminalBox.setEditable(false);
        terminalBox.setColumns(20);
        terminalBox.setRows(5);
        terminalScroll.setViewportView(terminalBox);

        continueButton.setText("Continuar");
        continueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continueButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout renderPanelLayout = new javax.swing.GroupLayout(renderPanel);
        renderPanel.setLayout(renderPanelLayout);
        renderPanelLayout.setHorizontalGroup(
            renderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        renderPanelLayout.setVerticalGroup(
            renderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 139, Short.MAX_VALUE)
        );

        resetarButton.setText("Resetar");
        resetarButton.setName("resetarButton"); // NOI18N
        resetarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(renderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(terminalScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(resetarButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(continueButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(renderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(continueButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(resetarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14)
                .addComponent(terminalScroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setAgent(Agent agent){
        
    }
   
    private void continueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continueButtonActionPerformed
      
       renderPanel.repaint();
            printer.update();
            
    }//GEN-LAST:event_continueButtonActionPerformed

    private void resetarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetarButtonActionPerformed

     
    }//GEN-LAST:event_resetarButtonActionPerformed
  
    //Para renderizar um objeto, utilize esta função para adiciona-lo à lista de exibição
    public void assignRenderizable(IRenderizable rend){
        renderPanel.assignRenderizable(rend);
    }
    
    //Retira o objeto da lista de renderização
    public void unasignRenderizable(IRenderizable rend){
        renderPanel.unassignRenderizable(rend);
    }
    
    //Para imprimir mensagens de um objeto, utilize esta função para adiciona-lo à lista de exibição
    public void assignPrintable(IPrintable p){
        printer.assignPrintable(p);
    }
    
    //Retira o objeto da lista de exibição
    public void unassignPrintable(IPrintable p){
        printer.unassignPrintable(p);
    }

    //Esta deve ser uma variável provisória - o agente deveria ser capaz 
    //de notificar uma mudança para esta classe de uma forma que um não 
    //fosse tão dependente do outro (criando um Observer por exemplo)
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton continueButton;
    private sistemasinteligentes.view.graphics.RenderPanel renderPanel;
    private javax.swing.JButton resetarButton;
    private javax.swing.JTextArea terminalBox;
    private javax.swing.JScrollPane terminalScroll;
    // End of variables declaration//GEN-END:variables
}
