package sistemasinteligentes.view.graphics;

import java.util.List;
import javax.swing.JOptionPane;
import sistemasinteligentes.model.search.AbstractSolver;
import sistemasinteligentes.model.Agent;
import sistemasinteligentes.model.search.ReverseWeightHeuristic;
import sistemasinteligentes.model.search.TableHeuristic;
import sistemasinteligentes.view.IPrintable;
import sistemasinteligentes.view.IRenderizable;


public class GUI extends javax.swing.JFrame {
    private Agent agent;
    private AbstractTextPrinter printer;
    private List<AbstractSolver> solvers;
    
    public GUI(List<AbstractSolver> solvers) {
        this.solvers = solvers;
        initComponents();
        printer = new JTextAreaPrinter(terminalBox);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        corAgente = new javax.swing.JPanel();
        corSolucao = new javax.swing.JPanel();
        corInicio = new javax.swing.JPanel();
        corObjetivo = new javax.swing.JPanel();
        corFronteira = new javax.swing.JPanel();
        corDestino = new javax.swing.JPanel();
        terminalScroll = new javax.swing.JScrollPane();
        terminalBox = new javax.swing.JTextArea();
        continueButton = new javax.swing.JButton();
        renderPanel = new sistemasinteligentes.view.graphics.RenderPanel();
        resetarButton = new javax.swing.JButton();
        labelAgente = new javax.swing.JLabel();
        labelSolucao = new javax.swing.JLabel();
        labelInicio = new javax.swing.JLabel();
        labelObjetivo = new javax.swing.JLabel();
        labelFronteira = new javax.swing.JLabel();
        labelDestino = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jComboBox2 = new javax.swing.JComboBox<AbstractSolver>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));
        setSize(new java.awt.Dimension(800, 600));

        corAgente.setBackground(Agent.AGENT_COLOR);
        corAgente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        javax.swing.GroupLayout corAgenteLayout = new javax.swing.GroupLayout(corAgente);
        corAgente.setLayout(corAgenteLayout);
        corAgenteLayout.setHorizontalGroup(
            corAgenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        corAgenteLayout.setVerticalGroup(
            corAgenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        corSolucao.setBackground(Agent.SOLUTION_COLOR);
        corSolucao.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        javax.swing.GroupLayout corSolucaoLayout = new javax.swing.GroupLayout(corSolucao);
        corSolucao.setLayout(corSolucaoLayout);
        corSolucaoLayout.setHorizontalGroup(
            corSolucaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        corSolucaoLayout.setVerticalGroup(
            corSolucaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        corInicio.setBackground(Agent.START_COLOR);
        corInicio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        javax.swing.GroupLayout corInicioLayout = new javax.swing.GroupLayout(corInicio);
        corInicio.setLayout(corInicioLayout);
        corInicioLayout.setHorizontalGroup(
            corInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        corInicioLayout.setVerticalGroup(
            corInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        corObjetivo.setBackground(Agent.OBJECTIVE_COLOR);
        corObjetivo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        javax.swing.GroupLayout corObjetivoLayout = new javax.swing.GroupLayout(corObjetivo);
        corObjetivo.setLayout(corObjetivoLayout);
        corObjetivoLayout.setHorizontalGroup(
            corObjetivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        corObjetivoLayout.setVerticalGroup(
            corObjetivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        corFronteira.setBackground(Agent.FRONTIER_COLOR);
        corFronteira.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        javax.swing.GroupLayout corFronteiraLayout = new javax.swing.GroupLayout(corFronteira);
        corFronteira.setLayout(corFronteiraLayout);
        corFronteiraLayout.setHorizontalGroup(
            corFronteiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        corFronteiraLayout.setVerticalGroup(
            corFronteiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        corDestino.setBackground(Agent.DESTINY_COLOR);
        corDestino.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        javax.swing.GroupLayout corDestinoLayout = new javax.swing.GroupLayout(corDestino);
        corDestino.setLayout(corDestinoLayout);
        corDestinoLayout.setHorizontalGroup(
            corDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        corDestinoLayout.setVerticalGroup(
            corDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        terminalBox.setEditable(false);
        terminalBox.setColumns(20);
        terminalBox.setRows(5);
        terminalScroll.setViewportView(terminalBox);

        continueButton.setText("Continuar");
        continueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continueButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout renderPanelLayout = new javax.swing.GroupLayout(renderPanel);
        renderPanel.setLayout(renderPanelLayout);
        renderPanelLayout.setHorizontalGroup(
            renderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 609, Short.MAX_VALUE)
        );
        renderPanelLayout.setVerticalGroup(
            renderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 161, Short.MAX_VALUE)
        );

        resetarButton.setText("Resetar");
        resetarButton.setName("resetarButton"); // NOI18N
        resetarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetarButtonActionPerformed(evt);
            }
        });

        labelAgente.setText("Agente");

        labelSolucao.setText("Solução");

        labelInicio.setText("Inicio");

        labelObjetivo.setText("Objetivo");

        labelFronteira.setText("Fronteira");

        labelDestino.setText("Destino");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        AbstractSolver[] as = new AbstractSolver[solvers.size()];
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(solvers.<AbstractSolver>toArray(as)));
        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2ItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(renderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(corAgente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(corSolucao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelSolucao)
                            .addComponent(labelAgente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(corInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelInicio)
                                .addGap(20, 20, 20))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(corObjetivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelObjetivo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(corFronteira, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelFronteira))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(corDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelDestino)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(resetarButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(continueButton))
                    .addComponent(terminalScroll, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 609, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(renderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelAgente)
                            .addComponent(corAgente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(corInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelInicio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(corSolucao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelSolucao)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(continueButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(resetarButton)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(labelFronteira)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelDestino))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(corFronteira, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(corDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(corObjetivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelObjetivo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(terminalScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setAgent(Agent agent){
        this.agent = agent;
    }
   
    private void continueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continueButtonActionPerformed
       agent.nextCycle();
       renderPanel.repaint();
       printer.update();     
    }//GEN-LAST:event_continueButtonActionPerformed

    private void resetarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetarButtonActionPerformed
        agent.resetAgent();
        renderPanel.repaint();
        printer.update();  
    }//GEN-LAST:event_resetarButtonActionPerformed

    private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2ItemStateChanged
        agent.setSolver((AbstractSolver) jComboBox2.getSelectedItem());
    }//GEN-LAST:event_jComboBox2ItemStateChanged
  
    //Para renderizar um objeto, utilize esta função para adiciona-lo à lista de exibição
    public void assignRenderizable(IRenderizable rend){
        renderPanel.assignRenderizable(rend);
    }
    
    //Retira o objeto da lista de renderização
    public void unasignRenderizable(IRenderizable rend){
        renderPanel.unassignRenderizable(rend);
    }
    
    //Para imprimir mensagens de um objeto, utilize esta função para adiciona-lo à lista de exibição
    public void assignPrintable(IPrintable p){
        printer.assignPrintable(p);
    }
    
    //Retira o objeto da lista de exibição
    public void unassignPrintable(IPrintable p){
        printer.unassignPrintable(p);
    }

    //Esta deve ser uma variável provisória - o agente deveria ser capaz 
    //de notificar uma mudança para esta classe de uma forma que um não 
    //fosse tão dependente do outro (criando um Observer por exemplo)
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton continueButton;
    private javax.swing.JPanel corAgente;
    private javax.swing.JPanel corDestino;
    private javax.swing.JPanel corFronteira;
    private javax.swing.JPanel corInicio;
    private javax.swing.JPanel corObjetivo;
    private javax.swing.JPanel corSolucao;
    private javax.swing.JComboBox<AbstractSolver> jComboBox2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel labelAgente;
    private javax.swing.JLabel labelDestino;
    private javax.swing.JLabel labelFronteira;
    private javax.swing.JLabel labelInicio;
    private javax.swing.JLabel labelObjetivo;
    private javax.swing.JLabel labelSolucao;
    private sistemasinteligentes.view.graphics.RenderPanel renderPanel;
    private javax.swing.JButton resetarButton;
    private javax.swing.JTextArea terminalBox;
    private javax.swing.JScrollPane terminalScroll;
    // End of variables declaration//GEN-END:variables
}
